// --- SETTINGS ---
const START_HOUR = 5;  // 5 AM
const END_HOUR = 23;   // 11 PM
const PX_PER_HOUR = 80; 

// --- STATE ---
let eventsData = [];
let editId = null;

function init() {
    const totalHours = END_HOUR - START_HOUR + 1; 
    const totalHeight = totalHours * PX_PER_HOUR;
    document.getElementById('calendarBody').style.height = totalHeight + 'px';

    const timeCol = document.getElementById('timeColumn');
    for (let i = 0; i < totalHours; i++) { 
        const h = START_HOUR + i;
        const cell = document.createElement('div');
        cell.className = 'time-cell';
        cell.innerHTML = formatHour(h);
        timeCol.appendChild(cell);
    }
}

// --- LOGIC ---
function addEvent() {
    const name = document.getElementById('subName').value;
    const day = document.getElementById('subDay').value;
    const start = document.getElementById('subStart').value;
    const end = document.getElementById('subEnd').value;
    const color = document.getElementById('subColor').value;

    if(!name || !start || !end) return alert("Please fill in all fields.");
    if(toDecimal(start) >= toDecimal(end)) return alert("End time must be after Start time.");

    const newEvent = {
        id: Date.now(),
        title: name,
        day: day,
        start: start,
        end: end,
        color: color,
        note: ""
    };
    eventsData.push(newEvent);
    renderMainGrid();
}

function renderMainGrid() {
    ['mon','tue','wed','thu','fri','sat','sun'].forEach(d => {
        document.getElementById(`col-${d}`).innerHTML = '';
    });
    eventsData.forEach(evt => drawEventOnGrid(evt, 'col-'));
}

function drawEventOnGrid(evt, prefixId) {
    const startDec = toDecimal(evt.start);
    const endDec = toDecimal(evt.end);
    if(startDec < START_HOUR || endDec > END_HOUR + 1) return; 

    const top = (startDec - START_HOUR) * PX_PER_HOUR;
    const height = (endDec - startDec) * PX_PER_HOUR;

    const el = document.createElement('div');
    el.className = `event-card ${evt.color}`;
    el.style.top = top + 'px';
    el.style.height = height + 'px';
    if(height < 60) el.classList.add('compact');

    el.innerHTML = `
        <span class="ev-time">${formatRange(evt.start, evt.end)}</span>
        <span class="ev-title">${evt.title}</span>
        ${evt.note ? `<span class="ev-note">${evt.note}</span>` : ''}
    `;
    
    if(prefixId === 'col-') {
        el.onclick = () => openModal(evt.id);
    }
    
    document.getElementById(`${prefixId}${evt.day}`).appendChild(el);
}

// --- EXPORT RENDERERS ---

function generateListHtmlForDays(dayKeys) {
    const daysMap = { mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday', sun: 'Sunday' };
    let html = '';
    let hasEvents = false;

    dayKeys.forEach(dayKey => {
        const daysEvents = eventsData.filter(e => e.day === dayKey);
        if(daysEvents.length === 0) return; 

        hasEvents = true;
        daysEvents.sort((a,b) => toDecimal(a.start) - toDecimal(b.start));

        html += `<div class="p-day-group"><div class="p-day-title">${daysMap[dayKey]}</div>`;
        daysEvents.forEach(evt => {
            html += `
                <div class="p-event-row">
                    <div class="p-time">
                        <span class="p-time-start">${formatSimple(evt.start)}</span>
                        <span class="p-time-end">${formatSimple(evt.end)}</span>
                    </div>
                    <div class="p-card ${evt.color}">
                        <h4>${evt.title}</h4>
                        ${evt.note ? `<span>📍 ${evt.note}</span>` : ''}
                    </div>
                </div>
            `;
        });
        html += `</div>`;
    });
    return { html, hasEvents };
}

function renderLandscapeHTML() {
    const container = document.getElementById('landscape-capture-area');
    const leftDays = ['mon', 'tue', 'wed'];
    const rightDays = ['thu', 'fri', 'sat', 'sun'];

    const leftContent = generateListHtmlForDays(leftDays);
    const rightContent = generateListHtmlForDays(rightDays);

    let html = `
        <div class="export-header">
            <h2>Weekly Schedule</h2>
            <p>Generated by Smart Scheduler</p>
        </div>
        <div class="export-two-col">
            <div class="export-col">
                ${leftContent.hasEvents ? leftContent.html : '<p style="color:#999; font-style:italic;">No classes early week.</p>'}
            </div>
            <div class="export-col">
                ${rightContent.hasEvents ? rightContent.html : '<p style="color:#999; font-style:italic;">No classes late week.</p>'}
            </div>
        </div>
    `;
    container.innerHTML = html;
}

function renderPortraitHTML() {
    const container = document.getElementById('portrait-capture-area');
    const allDays = ['mon','tue','wed','thu','fri','sat','sun'];
    const content = generateListHtmlForDays(allDays);

    let html = `
        <div class="export-header">
            <h2>Weekly Schedule</h2>
            <p>Generated by Smart Scheduler</p>
        </div>
        ${content.hasEvents ? content.html : '<p style="text-align:center; color:#999;">No classes scheduled.</p>'}
    `;
    container.innerHTML = html;
}

// --- DOWNLOADS ---
function downloadLandscape() {
    renderLandscapeHTML(); 
    const target = document.getElementById('landscape-capture-area');
    html2canvas(target, { backgroundColor: "#ffffff", scale: 2 }).then(canvas => {
        downloadCanvas(canvas, 'Schedule_Laptop.png');
    });
}

function downloadPortrait() {
    renderPortraitHTML(); 
    const target = document.getElementById('portrait-capture-area');
    html2canvas(target, { backgroundColor: "#ffffff", scale: 2 }).then(canvas => {
        downloadCanvas(canvas, 'Schedule_Phone.png');
    });
}

function downloadCanvas(canvas, filename) {
    const link = document.createElement('a');
    link.download = filename;
    link.href = canvas.toDataURL();
    link.click();
}

// --- HELPERS ---
function toDecimal(t) { let [h, m] = t.split(':').map(Number); return h + (m/60); }
function formatHour(h) { if(h===24) return "12 AM"; const ap = h>=12?"PM":"AM"; return `${h%12||12} ${ap}`; }
function formatSimple(t) { let [h, m] = t.split(':'); return `${parseInt(h)%12||12}:${m}`; }
function formatRange(s, e) {
    const f = t => { let [h, m] = t.split(':'); return `${parseInt(h)%12||12}:${m}`; };
    return `${f(s)} - ${f(e)}`;
}

function openModal(id) {
    editId = id;
    const evt = eventsData.find(e => e.id === id);
    document.getElementById('editTitle').value = evt.title;
    document.getElementById('editNote').value = evt.note;
    document.getElementById('editModal').style.display = 'flex';
}
function closeModal() { document.getElementById('editModal').style.display = 'none'; editId = null; }
function saveEdit() {
    const evt = eventsData.find(e => e.id === editId);
    if(evt) {
        evt.title = document.getElementById('editTitle').value;
        evt.note = document.getElementById('editNote').value;
        renderMainGrid();
    }
    closeModal();
}
function deleteEvent() {
    if(confirm("Delete this?")) {
        eventsData = eventsData.filter(e => e.id !== editId);
        renderMainGrid();
    }
    closeModal();
}
function resetAll() {
    if(confirm("Clear all?")) { eventsData = []; renderMainGrid(); }
}

init();
